add_newline = true

# Replace the "❯" symbol in the prompt with "➜"
[character]
symbol = "▲"
error_symbol = "▼"
vicmd_symbol = "△"
use_symbol_for_status = true

[cmd_duration]
style="yellow"

[aws]
style = "bold yellow"
symbol = "  "
displayed_items = "profile"
[aws.region_aliases]
ap-southeast-1 = "sg"
ap-southeast-2 = "au"

[kubernetes]
disabled = false

[conda]
symbol = " "

[golang]
symbol = " "

[hg_branch]
symbol = " "

[java]
symbol = " "

[memory_usage]
symbol = " "

[nodejs]
symbol = " "

[package]
symbol = " "

[php]
symbol = " "

[python]
symbol = " "

[ruby]
symbol = " "

[battery]
charging_symbol = "⚡️"
discharging_symbol = " "

[[battery.display]]
threshold = 20
style = "purple"
