add_newline = true

# Replace the "❯" symbol in the prompt with "➜"
[character]
success_symbol = "▲"
error_symbol = "▼"
vicmd_symbol = "△"

[cmd_duration]
style="yellow"

[aws]
style = "bold yellow"
format=' [$profile]($style) '

[aws.region_aliases]
ap-southeast-1 = "sg"

[[battery.display]]
threshold = 20
style = "purple"
