[buildPlans.iosevka-maya]
family = "Iosevka Maya"
spacing = "normal"
serifs = "sans"

[buildPlans.iosevka-maya.variants]
inherits = "ss12"

[buildPlans.iosevka-maya.variants.design]
turn-v = "curly"
capital-b = "more-asymmetric"
capital-d = "more-rounded"
capital-g = "toothless-rounded"
capital-i = "short-serifed"
capital-j = "serifless"
capital-k = "curly"
capital-m = "hanging"
capital-q = "taily"
capital-r = "curly"
capital-y = "curly"
a = "singlestorey-earless-corner-tailed"
b = "toothless-rounded"
d = "toothless-rounded"
f = "flat-hook-tailed"
g = "earless-corner"
h = "tailed"
i = "serifed-tailed"
k = "straight"
n = "earless-corner-straight"
p = "earless-corner"
r = "earless-rounded"
x = "curly"
y = "curly"
lambda = "straight"
zero = "unslashed"
one = "nobase"
four = "closed-non-crossing"
percent = "dots"
bar = "force-upright"
lig-ltgteq = "slanted"

[buildPlans.iosevka-maya.slopes]
upright = "normal"
italic = "italic"

[buildPlans.iosevka-maya.weights.light]
shape = 300
menu = 300
css = 300

[buildPlans.iosevka-maya.weights.regular]
shape = 400
menu = 400
css = 400

[buildPlans.iosevka-maya.weights.medium]
shape = 500
menu = 500
css = 500

[buildPlans.iosevka-maya.weights.semibold]
shape = 600
menu = 600
css = 600

[buildPlans.iosevka-maya.weights.bold]
shape = 700
menu = 700
css = 700
